INSERT INTO USERX (EMAIL, ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_USERNAME, CREATE_DATE) VALUES('veronika.viskey@yandex.ru',TRUE, 'Admin', 'Istrator', '{bcrypt}$2a$04$kzsueZwfqIQ22ssRRXMzmO8l/9X7v8vuqZCfV9prK0sgRKn1OvdJO', 'admin', 'admin', '2016-01-01 00:00:00')
INSERT INTO USERX_USERX_ROLE (USERX_USERNAME, ROLES) VALUES ('admin', 'ADMIN')
INSERT INTO USERX_USERX_ROLE (USERX_USERNAME, ROLES) VALUES ('admin', 'STUDENT')
INSERT INTO USERX (EMAIL, ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_USERNAME, CREATE_DATE) VALUES('lukas.geisler@student.uibk.ac.at', TRUE, 'Susi', 'Kaufgern', '{bcrypt}$2a$04$kzsueZwfqIQ22ssRRXMzmO8l/9X7v8vuqZCfV9prK0sgRKn1OvdJO', 'user1', 'admin', '2016-01-01 00:00:00')
INSERT INTO USERX_USERX_ROLE (USERX_USERNAME, ROLES) VALUES ('user1', 'STUDENT')
INSERT INTO USERX (EMAIL, ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_USERNAME, CREATE_DATE) VALUES('luca.rahm@student.uibk.ac.at', TRUE, 'Max', 'Mustermann', '{bcrypt}$2a$04$kzsueZwfqIQ22ssRRXMzmO8l/9X7v8vuqZCfV9prK0sgRKn1OvdJO', 'user2', 'admin', '2016-01-01 00:00:00')
INSERT INTO USERX_USERX_ROLE (USERX_USERNAME, ROLES) VALUES ('user2', 'STUDENT')
INSERT INTO USERX (EMAIL, ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_USERNAME, CREATE_DATE) VALUES('helin.kal@student.uibk.ac.at' ,TRUE, 'Elvis', 'The King', '{bcrypt}$2a$04$kzsueZwfqIQ22ssRRXMzmO8l/9X7v8vuqZCfV9prK0sgRKn1OvdJO', 'elvis', 'elvis', '2016-01-01 00:00:00')
INSERT INTO USERX_USERX_ROLE (USERX_USERNAME, ROLES) VALUES ('elvis', 'ADMIN')
INSERT INTO DECK (description,name,create_user_username,is_public) VALUES ('some useful english words with german translation ','english','admin','true')
INSERT INTO DECK (description,name,create_user_username,is_public) VALUES ('formulas of elements and its names ','chemistry','admin','false')
INSERT INTO DECK (description,name,create_user_username,is_public) VALUES ('dates of main events','history exam','user1','true')
INSERT INTO DECK (description,name,create_user_username,is_public) VALUES ('Law Of War (LoW) basic','Law','user1','false')
INSERT INTO DECK (description,name,create_user_username,is_public) VALUES ('description of deck 5 ','deck_5','elvis','false')
INSERT INTO DECK (description,name,create_user_username,is_public) VALUES ('description of deck 6 ','deck_6','elvis','false')
INSERT INTO CARD (create_Date,question,solution,deck_id) VALUES ('2022-12-07','direction','die Richtung',1)
INSERT INTO CARD (create_Date,question,solution,deck_id) VALUES ('2022-12-07','river','der Fluss',1)
INSERT INTO CARD (create_Date,question,solution,deck_id) VALUES ('2022-12-07','lake','der See',1)
INSERT INTO CARD (create_Date,question,solution,deck_id) VALUES ('2022-12-07','beach','der Strand',1)
INSERT INTO CARD (create_Date,question,solution,deck_id) VALUES ('2022-12-07','forest','der Wald',1)
INSERT INTO CARD (create_Date,question,solution,deck_id) VALUES ('2022-12-07','field','das Feld',1)
INSERT INTO CARD (create_Date,question,solution,deck_id) VALUES ('2022-12-07','Na₂CO₃','sodium carbonate',2)
INSERT INTO CARD (create_Date,question,solution,deck_id) VALUES ('2022-12-07','K₂CO₃','potassium carbonate',2)
INSERT INTO CARD (create_Date,question,solution,deck_id) VALUES ('2022-12-07','CuCO₃','copper(II) carbonate',2)
INSERT INTO CARD (create_Date,question,solution,deck_id) VALUES ('2022-12-07','MgCO₃','magnesium carbonate',2)
INSERT INTO CARD (create_Date,question,solution,deck_id) VALUES ('2022-12-07','BaSO₄','barium sulfate',2)
INSERT INTO CARD (create_Date,question,solution,deck_id) VALUES ('2022-12-09','Japan bombing','August 1945',3)
INSERT INTO CARD (create_Date,question,solution,deck_id) VALUES ('2022-12-09','Truman doctrin','March 1947',3)
INSERT INTO CARD (create_Date,question,solution,deck_id) VALUES ('2022-12-09','Communist takeover of Czechoslovakia','Feb 1948',3)
INSERT INTO CARD (create_Date,question,solution,deck_id) VALUES ('2022-12-09','Yugoslavia expelled','June 1948',3)
INSERT INTO CARD (create_Date,question,solution,deck_id) VALUES ('2022-12-09','Yalta','Feb 1945',3)
INSERT INTO CARD (create_Date,question,solution,deck_id) VALUES ('2022-12-09','choose the definition for LoW','the part of the international law that regulates the conduct of armed hostilities',4)
INSERT INTO CARD (create_Date,question,solution,deck_id) VALUES ('2022-12-09','The Geneva Conventions specify who is a(n):','Lawful combatant and civilian.',4)
INSERT INTO CARD (create_Date,question,solution,deck_id) VALUES ('2022-12-09','Under which LoW categorization would terrorist organizations or insurgent groups fall?','Unprivileged Belligerents',4)
INSERT INTO CARD (create_Date,question,solution,deck_id) VALUES ('2022-12-09','When does the full body of customary international law take effect?','At the beginning of aggressions',4)
INSERT INTO CARD (create_Date,question,solution,deck_id) VALUES ('2022-12-09','Which of the five principles of LoW regulates the use of all measures necessary to defeat the enemy?','Military Necessity',4)
INSERT INTO CARD (create_Date,question,solution,deck_id) VALUES ('2022-12-09','Which of the five principles of LoW forbids the infection of suffering, injury, or destruction deemed unnecessary to accomplish a legitimate military purpose?','Humanity',4)
INSERT INTO USER_DECK (username,deck_id) VALUES ('admin',1)
INSERT INTO USER_DECK (username,deck_id) VALUES ('admin',2)
INSERT INTO USER_DECK (username,deck_id) VALUES ('user1',3)
INSERT INTO USER_DECK (username,deck_id) VALUES ('user1',4)
INSERT INTO USER_DECK (username,deck_id) VALUES ('elvis',5)
INSERT INTO USER_DECK (username,deck_id) VALUES ('elvis',6)

INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_USERNAME, CREATE_DATE) VALUES(TRUE, 'SuperAdmin', 'surname', '{bcrypt}$2a$04$kzsueZwfqIQ22ssRRXMzmO8l/9X7v8vuqZCfV9prK0sgRKn1OvdJO', 'superAdmin', 'superAdmin', '2016-01-01 00:00:00')
INSERT INTO USERX_USERX_ROLE (USERX_USERNAME, ROLES) VALUES ('superAdmin', 'ADMIN')
